[general]
creation_date = "05/15/2025, 22:58:24"
model = "conv_lstm_v3"

[model_params]
size = 384
kmer_len = 9
num_out = 2
stride = 6
sequence_stride = 1

[modbases]
mod_bases = [ "a",]
offset = 0
reverse_signal = true
base_start_justify = true
mod_long_names_0 = "m6A"
chunk_context_0 = 300
chunk_context_1 = 300
kmer_context_bases_0 = 4
kmer_context_bases_1 = 4
motif = "DRACH"
motif_offset = 2
multi_prediction_output = true
chunk_size = 780

[refinement]
refine_do_rough_rescale = 1
refine_kmer_center_idx = 3

[sequence_encoder]
[[sequence_encoder.sublayers]]
type = "convolution"
insize = 36
size = 16
winlen = 5
stride = 1
padding = 2
activation = "tanh"

[[sequence_encoder.sublayers]]
type = "convolution"
insize = 16
size = 128
winlen = 15
stride = 1
padding = 7
activation = "tanh"


[signal_encoder]
[[signal_encoder.sublayers]]
type = "convolution"
insize = 1
size = 4
winlen = 5
stride = 1
padding = 2
activation = "tanh"

[[signal_encoder.sublayers]]
type = "convolution"
insize = 4
size = 16
winlen = 5
stride = 1
padding = 2
activation = "tanh"

[[signal_encoder.sublayers]]
type = "convolution"
insize = 16
size = 128
winlen = 15
stride = 6
padding = 7
activation = "tanh"

[encoder]
[[encoder.sublayers]]
type = "convolution"
insize = 256
size = 384
winlen = 5
stride = 1
padding = 2
activation = "tanh"

[[encoder.sublayers]]
type = "lstm"
size = 384
reverse = 0

[[encoder.sublayers]]
type = "lstm"
size = 384
reverse = 1

[[encoder.sublayers]]
type = "linear"
in_features = 384
out_features = 2
